name: CI Pipeline
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest #Entorno donde se ejecutará
    steps:
      - name: Descargar repo
        uses: actions/checkout@v4
      - name: Run test
        run: echo "Pipeline funcionando"
      - name: Build Docker image
        run: docker build -t devops-app ./semana3/app
      - name: Run test
        run: bash semana3/test.sh
      - name: Deploy simulacion
        run: echo "Deploy automático completado"
