name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest #Entorno donde se ejecutará
    permissions:
      contents: write
      
    steps:
      - name: Descargar repo
        uses: actions/checkout@v4
      - name: Run test
        run: echo "Pipeline funcionando"
      - name: Build Docker image
        run: docker build -t devops-app ./semana3/app
      - name: Run test
        run: bash semana3/test.sh
      - name: Deploy simulacion
        run: echo "Deploy automático completado"
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update stats
          commit_user_name: Dilan-2026
          commit_user_email: dilan-2026@github.com
          commit_author: Dilan-2026
