name: CI Pipeline
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest #Entorno donde se ejecutará
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Instalar dependecias
        run: npm install
      - name: Ejecutar test
        run: npm test
